### ISSUE TITLE
Which deb files to include for both 64 & 32-bit spins.

### ISSUE THREAD

**Issue by stacefauske** [stacefauske/bodhibuilder_2.18.x_all#5]
Discussion desired please:

1. Which deb files do we need to include in the bodhibuilder.deb package? (32 & 64-bit)
I think the packages for the 64-bit are good. Do we want to trim out any of the 32-bit packages, or do we need all of them?

2. Do we even want to include the actual packages, or just download the most recent version during an ISO spin?
-- PROS of excluding packages -- If we don't include the packages, there will probably be a less chance of compatibility problems. It will be easier to maintain. If a user is offline no packages will be downloaded and the size of the resulting ISO will be smaller. The bodhibuilder deb file will be smaller.
-- CONS of excluding packages -- If a user is offline and does an ISO spin, they will have 0 packages available to install. If a server is offline and a deb file can't be downloaded, there may be dependency issues.

**Comment by charlesbodhi** [comment]
I really prefer to offer an good offline experience to user when it comes to installing, think Astroboy and EscuelasLinux.

I would suggest to make being online a condition to use bodhibuilder because we are demanding a fully dist-upgraded system and want the most recent packages in the CD-repo. Bodhibuilder even exits when the building system is not dist-upgraded.

Following the above there is no need to have the packages in the bodhibuilder deb package.

I suggest adding libefivar1 to the 64bit package.list, being a dependency of libefiboot1 and 
add both libefiboot1 and libefivar1 to the 32bit package.list. Leave the all in, they will be useful for someone we don't even know.

Needs cleaning a lot of codesnippets no longer needed I'm afraid and checking that all that was written related to this for amd64 only now also is implemented for i386. Say thank you to the security people at Debian (APT).

**Comment by stacefauske** [comment]
Those are very good ideas and will make maintenance easier.

But for now, I will leave the deb files in. If nothing else, for the sake of Escuelas Linux. I am planning on adding a checkbox option to the GUI that will "Allow ISO creation if OS is not dist-upgraded". Once that change is in, I'll remove the deb files completely and it will be the user's responsibility to make sure they're online. This way the script will do an early check of dist-upgrade status and either plow through or exit out depending on what the user wants.

But I'm not sure how doable it's going to be. When I try to open bodhibuilder-gtk.glade with the glade program, it correctly says that bodhibuilder-gtk.glade is not compatible. Haven't had time to dig further into it, but bodhibuilder-gtk.glade will need some upgrades to GTK3 in order to make editing the GUI even possible. Will look at it more when I have time. May even have to edit the glade file using an old install of Ubuntu that will still be compatible.

If someone is more familiar with glade and can submit an updated bodhibuilder-gtk.glade file that would be welcome too!  :)

**Comment by stacefauske** [comment]
I'll also add your suggested deb files to 32 & 64 bit.

**Comment by stacefauske** [comment]
Deb files have been added
